### ISSUE TITLE
Postgres Master-role migration

### ISSUE THREAD

**Issue by kunalija** [t-matsuo/resource-agents#31]
Hi guys,

I have a postgres master/slave setup on SLES11SP3. For maintenance purpose I need a procedure to move the master role to the other node. I've tried the command 'crm_resource --resource msPostgresql --ban --master --host node1 --lifetime "P60S"'. Master role is actually moved to node2 but node1 stops with status disconnected (PGSQL.lock file remains in tmp directory). I have to manually delete the lock file and do a resource cleanup. Node1 should remain as slave after the master migration. Is it a bug or expected behaviour? 
PS What is the recommended version of pgsql ra agent, the one shipped with SLES or the latest from git? Thanks

**Comment by t-matsuo** [comment]
Hi kunalija

This repository is not maintained.
Could you write it into main(clusterlabs) repository?
https://github.com/ClusterLabs/resource-agents

**Comment by kunalija** [comment]
Sure, thanks
